name: Repo Review

on:
  push:
    branches: [main]
    paths:
      - 'pyproject.toml'
      - '.github/**'
      - 'LICENSE'
      - 'README.rst'
  pull_request:
    branches: [main]
    paths:
      - 'pyproject.toml'
      - '.github/**'
      - 'LICENSE'
      - 'README.rst'
  workflow_dispatch:

jobs:
  repo-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: scientific-python/repo-review@v0.12.3
        with:
          plugins: sp-repo-review
