name: Repo Review

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  repo-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: scientific-python/repo-review@v0.11
        with:
          plugins: sp-repo-review
